using TMPro;
using UnityEngine;

public class Snake : MonoBehaviour
{
    public float Speed { get { return _speed; }}

    [SerializeField] private TextMeshProUGUI _playerLoginText;
    [SerializeField] private int _playerLayer = 6;
    [SerializeField] private Tail _tailPrefab;
    [field: SerializeField] public Transform _head { get; private set; }
    [SerializeField] private float _speed = 2f;
    private Tail _tail;

    public void Init(int detailCount, Material skin, bool isPlayer = false)
    {
        _playerLoginText.text = PlayerSettings.Instance.Login;
        if (isPlayer)
        {
            _playerLoginText.gameObject.SetActive(false);

            gameObject.layer = _playerLayer;

            var childrens = GetComponentsInChildren<Transform>();
            for (int i = 0; i < childrens.Length; i++)
            {
                childrens[i].gameObject.layer = _playerLayer;
            }
        }

        _tail = Instantiate(_tailPrefab, transform.position, Quaternion.identity);
        _tail.Init(_head, _speed, detailCount, skin, _playerLayer, isPlayer);

        GetComponent<SetSkin>().Set(skin);
    }

    public void SetDetailCount(int detailCount)
    {
        _tail.SetDetailCount(detailCount);
    }

    public void Destroy(string clientID)
    {
        var detailPositions = _tail.GetDetailPositions();
        detailPositions.id = clientID;
        string json = JsonUtility.ToJson(detailPositions);
        MultiplayerManager.Instance.SendMessageToServer("gameOver", json);
        _tail.Destroy();
        Destroy(gameObject);
    }

    private void Update()
    {
        Move();
    }

    private void Move()
    {
        transform.position += _head.forward * Time.deltaTime * _speed;
    }

    public void SetRotation(Vector3 pointToLook)
    {
        _head.LookAt(pointToLook);
    }
}